In [1]:
import pandas as pd 
import numpy as np 
from scipy import stats
import matplotlib.pyplot as plt 

### Exercise15.3

In [25]:
df_t1501 = pd.DataFrame({
    'x1': [-1,1,-1,1,0,0,0],
    'x2': [-1,-1,1,1,0,0,0],
    'yield': [54.3,60.3,64.6,68.0,60.3,64.3,62.3]
})


df_t1501

,x1,x2,yield
0,-1,-1,54.3
1,1,-1,60.3
2,-1,1,64.6
3,1,1,68.0
4,0,0,60.3
5,0,0,64.3
6,0,0,62.3


In [26]:
df_e1503 = df_t1501.copy()
df_e1503['yield'] += 10
df_e1503

,x1,x2,yield
0,-1,-1,64.3
1,1,-1,70.3
2,-1,1,74.6
3,1,1,78.0
4,0,0,70.3
5,0,0,74.3
6,0,0,72.3


In [27]:
df_e1503['yield'].mean() # b0

np.float64(72.01428571428572)

In [28]:
df_e1503[['x1','yield']].prod(axis=1).sum()/2/2 # b1

np.float64(2.3500000000000014)

In [29]:
df_e1503[['x2','yield']].prod(axis=1).sum()/2/2 # b1

np.float64(4.5)

In [30]:
arr_e1503_x = np.concat((np.array([1]*7).reshape(7,1), df_e1503[['x1','x2']].to_numpy()), axis=1)
arr_e1503_y = df_e1503[['yield']].to_numpy()

arr_e1503_x, arr_e1503_y

(array([[ 1, -1, -1],
        [ 1,  1, -1],
        [ 1, -1,  1],
        [ 1,  1,  1],
        [ 1,  0,  0],
        [ 1,  0,  0],
        [ 1,  0,  0]]),
 array([[64.3],
        [70.3],
        [74.6],
        [78. ],
        [70.3],
        [74.3],
        [72.3]]))

In [31]:
np.linalg.inv(arr_e1503_x.T.dot(arr_e1503_x)).dot(arr_e1503_x.T.dot(arr_e1503_y))

array([[72.01428571],
       [ 2.35      ],
       [ 4.5       ]])

In [ ]:
arr_e1503_x.dot(np.linalg.inv(arr_e1503_x.T.dot(arr_e1503_x)).dot(arr_e1503_x.T.dot(arr_e1503_y))) # y_hat

array([[65.16428571],
       [69.86428571],
       [74.16428571],
       [78.86428571],
       [72.01428571],
       [72.01428571],
       [72.01428571]])

In [32]:
np.sqrt(np.linalg.inv(arr_e1503_x.T.dot(arr_e1503_x))*2.25) # standard errors

array([[0.56694671, 0.        , 0.        ],
       [0.        , 0.75      , 0.        ],
       [0.        , 0.        , 0.75      ]])

### Exercise 15.4

In [89]:
df_e1504 = df_t1501.copy()
df_e1504.iloc[0,2] = 50.3
df_e1504.iloc[3,2] = 72.0

df_e1504['x0'] = [1]*7
df_e1504['x12'] = df_e1504[['x1','x2']].prod(axis=1)
# df_e1504['x11+x22'] = (df_e1504[['x1','x2']]**2).sum(axis=1)/2 ## it seems adding this to the matrix gives the wrong b0
df_e1504

,x1,x2,yield,x0,x12
0,-1,-1,50.3,1,1
1,1,-1,60.3,1,-1
2,-1,1,64.6,1,-1
3,1,1,72.0,1,1
4,0,0,60.3,1,0
5,0,0,64.3,1,0
6,0,0,62.3,1,0


In [91]:
X_e1504 = df_e1504[['x0','x1','x2', 'x12']].to_numpy()
y_e1504 = df_e1504[['yield']].to_numpy()

In [92]:
np.linalg.inv(X_e1504.T.dot(X_e1504)).dot(X_e1504.T.dot(y_e1504)) # b0, b1, b2, b12

array([[62.01428571],
       [ 4.35      ],
       [ 6.5       ],
       [-0.65      ]])

In [93]:
np.sqrt(np.linalg.inv(X_e1504.T.dot(X_e1504))*2.25) # standard error of b0, b1, b2, b12

array([[0.56694671, 0.        , 0.        , 0.        ],
       [0.        , 0.75      , 0.        , 0.        ],
       [0.        , 0.        , 0.75      , 0.        ],
       [0.        , 0.        , 0.        , 0.75      ]])

In [94]:
# b11 + b22
df_e1504.iloc[:4, 2].sum()/4 - df_e1504.iloc[4:,2].sum()/3, np.sqrt(4*2.25/16 + 3*2.25/9)

(np.float64(-0.4999999999999929), np.float64(1.14564392373896))

### Exercise 15.5

In [95]:
df_e1505 = df_t1501.copy()
df_e1505 = df_e1505.iloc[:-1,:]
df_e1505['yield'] = [78.8,84.5,91.2,77.4,89.7,86.8]

df_e1505['x0'] = [1]*6
df_e1505['x12'] = df_e1505[['x1','x2']].prod(axis=1)
# df_e1505['x11+x22'] = (df_e1505[['x1','x2']]**2).sum(axis=1)/2 ## it seems adding this to the matrix gives the wrong b0
df_e1505

,x1,x2,yield,x0,x12
0,-1,-1,78.8,1,1
1,1,-1,84.5,1,-1
2,-1,1,91.2,1,-1
3,1,1,77.4,1,1
4,0,0,89.7,1,0
5,0,0,86.8,1,0


In [98]:
X_e1505 = df_e1505[['x0', 'x1', 'x2', 'x12']].to_numpy()
y_e1505 = df_e1505[['yield']].to_numpy()

In [ ]:
np.linalg.inv(X_e1505.T.dot(X_e1505)).dot(X_e1505.T.dot(y_e1505)) # b0 b1 b2 b12

array([[84.73333333],
       [-2.025     ],
       [ 1.325     ],
       [-4.875     ]])

In [ ]:
np.sqrt(np.linalg.inv(X_e1505.T.dot(X_e1505))*2.25) # standard error of b0 b1 b2 b12

array([[0.61237244, 0.        , 0.        , 0.        ],
       [0.        , 0.75      , 0.        , 0.        ],
       [0.        , 0.        , 0.75      , 0.        ],
       [0.        , 0.        , 0.        , 0.75      ]])

### Problem 15.5

In [119]:
df_e1506 = pd.DataFrame({
    'x1': [-np.sqrt(2), np.sqrt(2), 0, 0, 0, 0],
    'x2': [0, 0, -np.sqrt(2), np.sqrt(2), 0, 0],
    'yield': [83.3,81.2,81.2,79.5,87.0,86.0],
    })

df_e1506 = pd.concat((df_e1505.iloc[:,:3], df_e1506)).reset_index(drop=True)
df_e1506

,x1,x2,yield
0,-1.000000,-1.000000,78.8
1,1.000000,-1.000000,84.5
2,-1.000000,1.000000,91.2
3,1.000000,1.000000,77.4
4,0.000000,0.000000,89.7
5,0.000000,0.000000,86.8
6,-1.414214,0.000000,83.3
7,1.414214,0.000000,81.2
8,0.000000,-1.414214,81.2
9,0.000000,1.414214,79.5


In [120]:
df_e1506['x11'] = df_e1506['x1']**2
df_e1506['x12'] = df_e1506[['x1', 'x2']].prod(axis=1)
df_e1506['x22'] = df_e1506['x2']**2
df_e1506['x0'] = 1

In [121]:
X_e1506 = df_e1506[['x0', 'x1', 'x2', 'x11', 'x12', 'x22']].to_numpy()
y_e1506 = df_e1506[['yield']].to_numpy()

In [122]:
np.linalg.inv(X_e1506.T.dot(X_e1506)).dot(X_e1506.T.dot(y_e1506)) #b0 b1 b2 b11 b12 b22

array([[87.375     ],
       [-1.38373106],
       [ 0.36197962],
       [-2.14375   ],
       [-4.875     ],
       [-3.09375   ]])

In [123]:
(np.linalg.inv(X_e1506.T.dot(X_e1506))*2.25).round(3)#variance-covariance matrix

array([[ 0.562,  0.   ,  0.   , -0.281,  0.   , -0.281],
       [ 0.   ,  0.281,  0.   , -0.   ,  0.   , -0.   ],
       [ 0.   ,  0.   ,  0.281, -0.   ,  0.   , -0.   ],
       [-0.281, -0.   , -0.   ,  0.352,  0.   ,  0.07 ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.562,  0.   ],
       [-0.281, -0.   , -0.   ,  0.07 ,  0.   ,  0.352]])

### Figure 15.5

In [132]:
df_f1505 = pd.DataFrame({
    'x1': [-np.sqrt(2), np.sqrt(2), 0, 0, 0, 0],
    'x2': [0, 0, -np.sqrt(2), np.sqrt(2), 0, 0],
    'yield': [83.3,81.2,81.2,79.5,87.0,86.0],
    })

df_f1505 = pd.concat((df_e1505.iloc[:,:3], df_f1505)).reset_index(drop=True)


df_f1505['x11'] = df_f1505['x1']**2
df_f1505['x12'] = df_f1505[['x1', 'x2']].prod(axis=1)
df_f1505['x22'] = df_f1505['x2']**2
df_f1505['x0'] = 1

df_f1505['x111'] = df_f1505['x1']**3
df_f1505['x222'] = df_f1505['x2']**3
df_f1505['x112'] = df_f1505[['x11','x2']].prod(axis=1)
df_f1505['x122'] = df_f1505[['x22','x1']].prod(axis=1)

df_f1505

,x1,x2,yield,x11,x12,x22,x0,x111,x222,x112,x122
0,-1.000000,-1.000000,78.8,1.0,1.0,1.0,1,-1.000000,-1.000000,-1.0,-1.0
1,1.000000,-1.000000,84.5,1.0,-1.0,1.0,1,1.000000,-1.000000,-1.0,1.0
2,-1.000000,1.000000,91.2,1.0,-1.0,1.0,1,-1.000000,1.000000,1.0,-1.0
3,1.000000,1.000000,77.4,1.0,1.0,1.0,1,1.000000,1.000000,1.0,1.0
4,0.000000,0.000000,89.7,0.0,0.0,0.0,1,0.000000,0.000000,0.0,0.0
5,0.000000,0.000000,86.8,0.0,0.0,0.0,1,0.000000,0.000000,0.0,0.0
6,-1.414214,0.000000,83.3,2.0,-0.0,0.0,1,-2.828427,0.000000,0.0,-0.0
7,1.414214,0.000000,81.2,2.0,0.0,0.0,1,2.828427,0.000000,0.0,0.0
8,0.000000,-1.414214,81.2,0.0,-0.0,2.0,1,0.000000,-2.828427,-0.0,0.0
9,0.000000,1.414214,79.5,0.0,0.0,2.0,1,0.000000,2.828427,0.0,0.0


In [151]:
X_f1505 = df_f1505[['x0','x1','x2','x11','x12','x22']].to_numpy()
y_f1505 = df_f1505[['yield']].to_numpy()

In [152]:
np.linalg.inv(X_f1505.T.dot(X_f1505)).dot(X_f1505.T.dot(y_f1505))

array([[87.375     ],
       [-1.38373106],
       [ 0.36197962],
       [-2.14375   ],
       [-4.875     ],
       [-3.09375   ]])

In [153]:
(np.linalg.inv(X_f1505.T.dot(X_f1505))*2.25).round(3)

array([[ 0.562,  0.   ,  0.   , -0.281,  0.   , -0.281],
       [ 0.   ,  0.281,  0.   , -0.   ,  0.   , -0.   ],
       [ 0.   ,  0.   ,  0.281, -0.   ,  0.   , -0.   ],
       [-0.281, -0.   , -0.   ,  0.352,  0.   ,  0.07 ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.562,  0.   ],
       [-0.281, -0.   , -0.   ,  0.07 ,  0.   ,  0.352]])